# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Release pre-built APK to GitHub Releases"
  lane :release do
    apk_path = File.expand_path("../signed_release.apk", __dir__)

    gradle_file = File.expand_path("../androidApp/build.gradle.kts", __dir__)
    gradle_content = File.read(gradle_file)
    version_code = gradle_content[/versionCode\s*=\s*(\d+)/, 1]

    changelog_file = File.expand_path("metadata/android/en-US/changelogs/#{version_code}.txt", __dir__)

    release_notes = if version_code && File.exist?(changelog_file)
                      File.read(changelog_file).strip
                    else
                      "Bug fixes and performance improvements."
                    end

    set_github_release(
      repository_name: "ghostbyte-dev/pixelix",
      api_token: ENV["GITHUB_TOKEN"],
      tag_name: ENV["GITHUB_REF_NAME"],
      name: "Pixelix " + (ENV["GITHUB_REF_NAME"] || "Dev Build"),
      description: release_notes,
      upload_assets: [apk_path],
      is_draft: true
    )
  end
end
