# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

private_lane :get_android_version_code do
  gradle_file = File.expand_path("../androidApp/build.gradle.kts", __dir__)
  gradle_content = File.read(gradle_file)
  gradle_content[/versionCode\s*=\s*(\d+)/, 1]
end

private_lane :get_android_version_name do
  gradle_file = File.expand_path("../androidApp/build.gradle.kts", __dir__)
  gradle_content = File.read(gradle_file)
  gradle_content[/versionName\s*=\s*"([^"]+)"/, 1]
end

private_lane :get_release_notes do |options|
  version_code = options[:version_code]
  changelog_file = File.expand_path("metadata/android/en-US/changelogs/#{version_code}.txt", __dir__)

  if version_code && File.exist?(changelog_file)
    File.read(changelog_file).strip
  else
    "Bug fixes and performance improvements."
  end
end

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Create a draft GitHub release with pre-built APK"
  lane :github_release do
    version_code = get_android_version_code
    version_name = get_android_version_name
    notes = get_release_notes(version_code: version_code)

    original_apk_path = File.expand_path("../androidApp/build/outputs/apk/release/androidApp-release.apk", __dir__)
    renamed_apk_path = File.expand_path("../androidApp/build/outputs/apk/release/pixelix_#{version_name}.apk", __dir__)
    FileUtils.cp(original_apk_path, renamed_apk_path)

    set_github_release(
      repository_name: "ghostbyte-dev/pixelix",
      api_bearer: ENV["GITHUB_TOKEN"],
      tag_name: ENV["GITHUB_REF_NAME"],
      name: "Pixelix " + (ENV["GITHUB_REF_NAME"] || "Dev Build"),
      description: notes,
      upload_assets: [renamed_apk_path],
      is_draft: true
    )
  end
  lane :playstore do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    upload_to_play_store(
      track: 'internal',
      aab: 'androidApp/build/outputs/bundle/release/androidApp-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
    )
  end
  lane :release do
    github_release
    playstore
  end
end
